### ISSUE TITLE
gamenet: invalidid -> invalid id

### ISSUE THREAD

**Issue by ChillerDragon** [heinrich5991/libtw2#102]
Drunk teeworlds devs thought invalidid is one word. Can we fix that in libtw2?

https://github.com/heinrich5991/libtw2/blob/f3c8840d756bc06e436656c16f48f02bcb4ce8b3/gamenet/generate/spec/teeworlds-0.7.5.json#L84

**Comment by heinrich5991** [comment]
Since that is generated, it should probably be fixed in upstream instead. Any changes there will be reflected here. Upstream is obviously unresponsive though.

https://github.com/teeworlds/teeworlds/blob/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/datasrc/network.py#L15C45-L15C59

**Comment by heinrich5991** [comment]
@ChillerDragon Could you open an upstream PR?

**Comment by ChillerDragon** [comment]
https://github.com/teeworlds/teeworlds/pull/3251

**Comment by ChillerDragon** [comment]
lez go its merged upstream
