### ISSUE TITLE
gamenet: connless 0.7 token is not a u8

### ISSUE THREAD

**Issue by ChillerDragon** [heinrich5991/libtw2#106]
https://github.com/heinrich5991/libtw2/blob/9bfd8a6a0d1d9665202c01868fe1974daaa99fcc/gamenet/generate/loader.py#L183

this should be a int

https://github.com/teeworlds/teeworlds/blob/c56fa9e6a20cfc9d7d16502e18c7d7633acdf492/src/engine/client/serverbrowser.cpp#L298

![image](https://github.com/user-attachments/assets/976941e4-b2b8-4c75-ac66-7e2984eccd4c)

**Comment by heinrich5991** [comment]
Yea, looks like a bug.

**Comment by ChillerDragon** [comment]
This is not fixed? There were no changes in the rust code. The generation seems unsupported for this field.

**Comment by ChillerDragon** [comment]
Ah I see the force push fixed it never mind.

**Comment by heinrich5991** [comment]
Sorry about the force push.
