### ISSUE TITLE
gamenet: json spec does not differentiate snap objects from snap events

### ISSUE THREAD

**Issue by ChillerDragon** [heinrich5991/libtw2#108]
this is an event

https://github.com/heinrich5991/libtw2/blob/ee98f464a958eae49e65afb02d4cbcf9ebee1d4d/gamenet/generate/spec/teeworlds-0.7.5.json#L869-L881

this is an object

https://github.com/heinrich5991/libtw2/blob/ee98f464a958eae49e65afb02d4cbcf9ebee1d4d/gamenet/generate/spec/teeworlds-0.7.5.json#L775-L785

https://github.com/teeworlds/teeworlds/blob/c56fa9e6a20cfc9d7d16502e18c7d7633acdf492/datasrc/network.py#L252-L258

https://github.com/teeworlds/teeworlds/blob/c56fa9e6a20cfc9d7d16502e18c7d7633acdf492/datasrc/network.py#L194-L199

**Comment by heinrich5991** [comment]
Is there any difference between snap objects and snap events? I wasn't aware of any difference.

**Comment by ChillerDragon** [comment]
There is a conceptual difference. I think it would be nice to keep that in the spec. An event is supposed to be only consumed and displayed once. It is like a particle effect or sound while a object is a more permanent entity in the world.

In the teeworlds code they are [processed in different places in the code](https://github.com/teeworlds/teeworlds/blob/c56fa9e6a20cfc9d7d16502e18c7d7633acdf492/src/game/client/gameclient.cpp#L1058-L1101). Events can also been seen as less important and objects could be prioritized on resource shortage.

As a [user of the spec](https://gitlab.com/teeworlds-network/twnet_parser/-/blob/6ef29e7d340dbcf1c194e690d333957d449050c8/scripts/generate_messages.py#L928-931) I would like to know what is an event and what is an object.

**Comment by heinrich5991** [comment]
I can see that you want to generate different names for them, so that's probably enough to add that feature.

**Comment by heinrich5991** [comment]
I can see the naming reason, and that for that it should be sufficient to put a string `"event"` into the `"attributes"` array.

I don't see for what other reason you'd need to annotate the structs automatically. E.g. Teeworlds source code does not distinguish between them at all in an automated fashion, except for the struct naming. The dissector wouldn't care at all, probably. In your example, I also only see naming.

**Comment by ChillerDragon** [comment]
Yea sure if "event" in "attributes" is all you want to give. I'll take it.

**Comment by heinrich5991** [comment]
I'm interested in where and whether this is used, please comment if you take advantage of this flag.

**Comment by ChillerDragon** [comment]
It is now exposed as part of the snap item name to users of my parsing library

https://gitlab.com/teeworlds-network/twnet_parser/-/commit/4b76d24eea00c31d3338bc6dd5276ad6454c4f20
