### ISSUE TITLE
teehistorian_index: Run on stdin

### ISSUE THREAD

**Issue by def-** [heinrich5991/libtw2#17]
Specifying `-` for stdin as the directory/file (`--help` says just directory but file also works) does not work, so instead I have to create a temporary file:

    xzcat $1 > /tmp/${1:t:r} && ./teehistorian_index /tmp/${1:t:r} | tail -n-1 | cut -d',' -f2- >> ${1:h}/index.txt && rm /tmp/${1:t:r}

**Comment by def-** [comment]
Thanks!

**Comment by def-** [comment]
Actually the fix doesn't seem to work:

    xzcat data/irn/00042670-041e-49ed-90dd-efc4e09c6166.teehistorian.xz | /media/teehistorian/teehistorian_index --ignore-ext -

prints nothing.

**Comment by heinrich5991** [comment]
Does it work now?

**Comment by def-** [comment]
Nope, still empty output.

**Comment by heinrich5991** [comment]
```
$ xzcat 000012a6-2374-44d9-89fe-7dc2a910f65d.teehistorian.xz | path/to/teehistorian_index --ignore-ext /dev/stdin
path,game_uuid,timestamp,map_name,map_crc,map_size
/dev/stdin,000012a6-2374-44d9-89fe-7dc2a910f65d,2017-10-15T19:39:18+02:00,"Sonne, Mond und Sterne",f77bcc82,576351
```
For me, it seems to work. ^ :/

Can you give me an strace of the failed run?

**Comment by def-** [comment]
Apparently I copied the wrong teehistorian_index. Initially I had it in tools/target/, now it is just in target/. Now it works.
