### ISSUE TITLE
[Question] Do huffman.md doc is outdated ?

### ISSUE THREAD

**Issue by moien007** [heinrich5991/libtw2#4]
Hi, 

Do huffman.md doc is outdated ?

**Comment by heinrich5991** [comment]
Not that I'm aware of. What problem are you experiencing?

**Comment by heinrich5991** [comment]
Fixed formatting of the document in https://github.com/heinrich5991/libtw2/commit/5165560f85d6b11499deb33a381be0abf673e8ff.

**Comment by moien007** [comment]
Actually i create this issues just for ensure. (sorry)
thanks for info.

**Comment by heinrich5991** [comment]
> Can you provide more info about decompressing Huffman streams ?

What do you need? There's a decompression implementation in the crate; do you want more information in the documentation? What are you building? Can I help you? :)
