### ISSUE TITLE
teehistorian2demo: Teehistorian(UnexpectedEnd) (exit code: 1)

### ISSUE THREAD

**Issue by murpii** [heinrich5991/libtw2#47]
getting (exit code: 1) error while trying to convert:
18ea384e-42c7-428a-8abd-4f568e392b73.teehistorian
locally on Windows 10 64bit.

I dunno if that's related but:
The demo I get as output isn't the full demo, I think. It's missing the actual run from Aoe, iParano and coradax.
This probably also happens on Learath's teehistorian2demo version because he gets the same demo output as I do locally.

**Comment by heinrich5991** [comment]
This error happens when a teehistorian file ends without the end signature. It likely means that you have an incomplete teehistorian file.

Can you give me the exact length in bytes of your teehistorian file?

I get:

```
> stat data/ger2/18ea384e-42c7-428a-8abd-4f568e392b73.teehistorian | grep -i size
  Size: 26572132 […]
```

**Comment by murpii** [comment]
15.107.069 bytes in size

**Comment by heinrich5991** [comment]
Sounds like the issue was the short teehistorian file.
