### ISSUE TITLE
gamenet: missing connless info (inf3)

### ISSUE THREAD

**Issue by ChillerDragon** [heinrich5991/libtw2#77]
https://github.com/heinrich5991/libtw2/blob/7885c99974ee445ce13297b72ae3e7c6ea3b969d/gamenet/generate/spec/teeworlds-0.7.5.json#L1127-L1133

there is "request info" which maps to GETINFO here

https://github.com/teeworlds/teeworlds/blob/26d24ec061d44e6084b2d77a9b8a0a48e354eba6/src/mastersrv/mastersrv.h#L27

but the "info" one is missing

**Comment by heinrich5991** [comment]
Yep, that's missing. Would need to be added somewhere around here:

https://github.com/heinrich5991/libtw2/blob/7885c99974ee445ce13297b72ae3e7c6ea3b969d/gamenet/generate/loader.py#L167-L207
