### ISSUE TITLE
Extend json spec to include vital flag

### ISSUE THREAD

**Issue by ChillerDragon** [heinrich5991/libtw2#91]
https://github.com/heinrich5991/libtw2/blob/b9286674da94d3d45b9c10ffce517af394e2d58c/gamenet/generate/spec/teeworlds-0.7.5.json

Some messages are supposed to send the vital flag and others do not. This information is missing the the spec.

**Comment by heinrich5991** [comment]
The only messages not supposed to be sent as vital messages (it's more than a flag, they get sequence numbers, get re-sent), are `INPUT` an `SNAP_*` messages, right?

**Comment by ChillerDragon** [comment]
Yea I think so.

**Comment by ChillerDragon** [comment]
Cool thanks
